---
version: "3"

vars:
  # add variables here
  {}

dotenv: [".config.env"]

env:
  EDITOR: nano

includes:
  init: .taskfiles/init.yml
  ansible: .taskfiles/ansible.yml

tasks:

  default:
    - task --list-all

  init:
    desc: Prepare WSL2 to meet the pre-requisites
    cmds:
    - task: init:install-ansible
    - task: init:install-brew
