---

- name: Ensure `.config` directory exists
  become: false
  file:
    path: "{{ ansible_env.HOME }}/.config"
    state: directory
  tags:
    - dotfiles

- name: Ensure `bin` directory exists
  become: false
  file:
    path: "{{ ansible_env.HOME }}/bin"
    state: directory
  tags:
    - dotfiles

- name: Add 'Homebrew' to 'bashrc'
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"'
  tags:
    - dotfiles

- name: Add 'Direnv' to 'bashrc'
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: 'eval "$(direnv hook bash)"'
  tags:
    - dotfiles

- name: Add 'Starship' to 'bashrc'
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: 'eval "$(starship init bash)"'
  tags:
    - dotfiles

- name: Ensure Starship config is present
  copy:
    src: "{{ role_path }}/files/starship.toml"
    dest: "{{ ansible_env.HOME }}/.config/starship.toml"
  tags:
    - dotfiles

- name: Add Starship config file to 'bashrc'
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: 'export STARSHIP_CONFIG=~/.config/starship.toml'
  tags:
    - dotfiles
