- name: Download node.js config
  get_url:
    url: https://deb.nodesource.com/setup_18.x
    dest: /tmp/nodesource_setup.sh

- name: Configure node.js
  become: yes
  command: "bash /tmp/nodesource_setup.sh" 

- name: Installing node.js packages
  become: yes
  become_method: sudo
  apt:
    pkg:
      - nodejs