---
- name: Check if node.js is installed
  stat:
    path: "/usr/bin/node"
  register: node_is_installed

- name: Download node.js config
  when: "not node_is_installed.stat.exists"
  get_url:
    url: https://deb.nodesource.com/setup_18.x
    dest: /tmp/nodesource_setup.sh

- name: Configure node.js
  when: "not node_is_installed.stat.exists"
  become: yes
  command: "bash /tmp/nodesource_setup.sh" 

- name: Installing node.js packages
  when: "not node_is_installed.stat.exists"
  become: yes
  become_method: sudo
  apt:
    pkg:
      - nodejs

- name: Configure npm for globals
  blockinfile:
    state: present
    insertafter: EOF
    dest: ~/.bashrc
    marker_begin: "begin NPM ansible marker"
    marker_end: "end NPM ansible marker"
    content: |
      mkdir -p ~/.npm-global
      npm config set prefix '~/.npm-global'
      export PATH=~/.npm-global/bin:$PATH/bin:$PATH
