---
- name: Add RVM repository to apt
  become: yes
  apt_repository:
    repo: ppa:rael-gc/rvm

- name: Update packages list
  become: yes
  apt:
    update_cache: yes

- name: Installing RVM
  become: yes
  become_method: sudo
  apt:
    pkg:
      - rvm

- name: Add RVM to ~/.bashrc
  blockinfile:
    state: present
    insertafter: EOF
    dest: ~/.bashrc
    marker_begin: "begin RVM ansible marker"
    marker_end: "end RVM ansible marker"
    content: |
      source "/etc/profile.d/rvm.sh"

- name: Add User to RVM group
  become: yes
  user:
    name: "{{ lookup('env','USER') }}"
    groups: rvm
    append: yes