---

- name: Install 'aws-azure-login' CLI
  npm:
    name: aws-azure-login
    global: yes
    unsafe_perm: yes
  tags:
    - sporting
    - aws-azure

- name: Copy Sporting SSO config
  copy:
    src: "{{ role_path }}/files/config"
    dest: "{{ ansible_env.HOME }}/.aws/config"
  tags:
    - dotfiles
    - sporting
    - aws-azure

- name: Ensure you can `sshuttle` to OY
  copy:
    src: "{{ role_path }}/files/oy-sshuttle"
    dest: "{{ ansible_env.HOME }}/bin/oy-sshuttle"
  tags:
    - dotfiles

- name: Set execute permission
  file:
    path: "{{ ansible_env.HOME }}/bin/oy-sshuttle"
    mode: u+x

# This might be  reviewed, it is based on https://www.sindastra.de/p/679/no-sudo-password-in-wsl
- name: Add sudoers rule for fabrice to run sshuttle without a password 
  command: |
    echo "`whoami` ALL=(ALL) NOPASSWD: /home/fabrice/bin/oy-sshuttle" | sudo tee /etc/sudoers.d/`whoami` && sudo chmod 0440 /etc/sudoers.d/`whoami`
