---

- name: Install 'aws-azure-login' CLI
  npm:
    name: aws-azure-login
    global: yes
    unsafe_perm: yes
  tags:
    - sporting
    - aws-azure

- name: Copy Sporting SSO config
  copy:
    src: "{{ role_path }}/files/config"
    dest: "{{ ansible_env.HOME }}/.aws/config"
  tags:
    - dotfiles
    - sporting
    - aws-azure-