---
- name: Add python repository to apt
  become: yes
  apt_repository:
    repo: ppa:deadsnakes/ppa

- name: Update packages list
  become: yes
  apt:
    update_cache: yes

- name: Installing Python
  become: yes
  become_method: sudo
  apt:
    pkg:
      - software-properties-common
      - python3.9
      - python3.9-distutils
      - python3.9-venv

- name: Re-generate pip
  become: yes
  command: "python3.9 -m ensurepip"
