---
- name: Add python repository to apt
  become: yes
  apt_repository:
    repo: ppa:deadsnakes/ppa

- name: Update packages list
  become: yes
  apt:
    update_cache: yes

- name: Installing Python
  become: yes
  become_method: sudo
  apt:
    pkg:
      - software-properties-common
      - "python{{ python_version }}"
      - "python{{ python_version }}-distutils"
      - "python{{ python_version }}-venv"

- name: Check if pip3 is installed
  stat:
    path: "/usr/local/bin/pip3"
  register: pip3_is_installed

- name: Re-generate pip
  when: "not pip3_is_installed.stat.exists"
  become: yes
  command: "python{{ python_version }} -m ensurepip"
