---
- name: Check if wsl.conf is installed
  stat:
    path: '/etc/wsl.conf'
  register: wsl_conf_is_installed

- name: Enable Systemd and Fix networking - https://gist.github.com/coltenkrauter/608cfe02319ce60facd76373249b8ca6
  become: true
  when: 'not wsl_conf_is_installed.stat.exists'
  copy:
    dest: '/etc/wsl.conf'
    content: |
      [boot]
      systemd=true
      [network]
      generateResolvConf = false

- name: Shutdown WSL (to restart WSL)
  when: 'not wsl_conf_is_installed.stat.exists'
  command: wsl.exe --shutdown
