---
- name: Update packages list
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 43200

- name: Install updates
  become: true
  apt:
    upgrade: yes

- name: Installing Common Apt packages
  become: true
  become_method: sudo
  apt:
    pkg: "{{  apt_packages  }}"
    state: present