---
- name: Installing openjdk-17 LTS
  become: yes
  become_method: sudo
  apt:
    pkg:
      - openjdk-17-jdk
      - openjdk-17-jre

- name: Check if gradle is installed
  stat:
    path: "{{ gradle_exec }}"
  register: gradle_is_installed

- name: Creates directory
  become: yes
  file:
    path: "{{ gradle_path }}"
    state: directory

- name: Install Gradle
  when: "not gradle_is_installed.stat.exists"
  become: yes
  unarchive:
    src: "https://services.gradle.org/distributions/gradle-{{ gradle_version }}-bin.zip"
    dest: "{{ gradle_path }}"
    remote_src: yes

- name: Add JAVA vars to ~/.bashrc
  blockinfile:
    state: present
    insertafter: EOF
    dest: ~/.bashrc
    marker_begin: "begin JAVA ansible marker"
    marker_end: "end JAVA ansible marker"
    content: |
      export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which javac))))
      export PATH=/opt/gradle/gradle-{{ gradle_version }}/bin:$PATH
